version: '3'
services:
  db:
    image: postgres:14-alpine
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

  adminer:
      image: adminer
      restart: always
      ports:
      - ${ADMIN_PORT}:8080

  # app:
  #   image: teneno-api
  #   ports:
  #     - "5500:5500"
  #   restart: unless-stopped