version: '3'
services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres
    hostname: postgres
    ports:
      - ${DB_PORT}:5432
    env_file:
      - .env
    restart: always
    volumes:
      - ./.docker/postgres/postgres-data:/var/lib/postgresql/data
    networks:
      - postgres-network
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: pg_isready
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: dockette/adminer:pgsql
    container_name: adminer
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - ${ADMIN_PORT}:80
    networks:
      - postgres-network
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - ./.docker/adminer/adminer-data:/var/lib/pgadmin

  app:
    image: teneno
    container_name: teneno
    volumes:
      - ./:/app
    ports:
      - 5500:5500
    restart: unless-stopped
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint:
      - /bin/sh
    command:
      - -c
      - npm run start:dev
    networks:
      - postgres-network
    depends_on:
        - postgres
    env_file:
        - .env

networks:
  postgres-network:
