version: '3'
services:
  db:
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1233456789
      POSTGRES_DB: teneno-api
  # app:
  #   image: teneno-api
  #   ports:
  #     - "5500:5500"
  #   restart: unless-stopped