name: teneno-api

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    node-version-test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [14.x, 16.x]
        steps:
            - name: Checkout Code
              uses: actions/checkout@v2
            - name: Set up nodejs version ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'
            - name: Install package
              run: npm install
            - name: Format code
              run: npm run lint
            - name: Build
              run: npm run build
            - name: Test
              run: npm run test
    gallium-alpine-test:
        needs: node-version-test
        runs-on: ubuntu-latest
        container:
            image: node:gallium-alpine
        steps:
            - name: Checkout Code
              uses: actions/checkout@v2
            - name: Install package
              run: npm install
            - name: Test
              run: npm run test
    build-image:
        needs: gallium-alpine-test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v2
            - name: build container image
              run: docker build -t thuongtruong1009/teneno-api:${{ github.sha }} .
            - name: Login to DockerHub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}
            - name: push container image
              run: docker push thuongtruong1009/teneno-api:${{ github.sha }}
